// <auto-generated />
namespace MyForum.Migrations.ForumDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Forum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Forum));
        
        string IMigrationMetadata.Id
        {
            get { return "201610050759087_Forum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
